name: SCA Check
on:
  push:
    branches: [ main ]  # Adjust this to your master branch name
  pull_request:
    branches: [ main ]  # Optionally run on PRs
jobs:
  sca-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create project zip
        run: |
          zip -r project.zip . -x "*.git*" "*/node_modules/*" "*/vendor/*" "*.zip"
      
      - name: Perform SCA Scan
        id: sca
        run: |
          RESPONSE=$(curl -X POST             -H "Client-ID: ${{ secrets.INTRUCEPT_CLIENT_ID }}"             -H "Client-Secret: ${{ secrets.INTRUCEPT_CLIENT_SECRET }}"             -F "projectZipFile=@project.zip"             -F "applicationId=${{ secrets.INTRUCEPT_APPLICATION_ID }}"             -F "scanName=SCA Scan - ${{ github.sha }}"             -F "language=python"             https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)          
          
          
          VULNS_TABLE=$(echo $RESPONSE | jq -r '.vulnsTable')
          echo "Vulnerabilities Table:"
          echo "$VULNS_TABLE"
